apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
---
# MESH
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-system
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
# NAMESPACE
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: test-permissive
  namespace: test
spec:
  mtls:
    mode: PERMISSIVE
---
# WORKLOAD
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: httpbin2-default-strict
  namespace: default
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app: httpbin2